services:
  ffmpeg-tool:
    build:
      context: .
    container_name: ffmpeg-live-transcoder-docker
    command: python app.py /watch /output --poll 5
    volumes:
      - ./watch:/watch
      - ./output:/output
    environment:
      PYTHONUNBUFFERED: "1"
    restart: unless-stopped
